### ISSUE TITLE
Mongodb support

### ISSUE THREAD

**Issue by chanwit** [akrabat/lambda-php-sls-hello-world#6]
Hi

I'm really exciting with PHP on Lambda. I saw that composer also gets installed into the layer.

My question is how to get PHP Lambda to work with PECL mongodb driver?

Thank you for this great project.

cheers

**Comment by akrabat** [comment]
Look at [bref.sh](https://bref.sh). It has it available to enable I believe.

Otherwise, you need to build your PHP layer with the mongo driver by updating the Dockerfile.
